version: '3.9'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
    - DB_URL=postgres://postgres:postgres@db:5432/?sslmode=disable
    ports:
    - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.1-alpine
    environment:
    - PGUSER=postgres
    - PGPASSWORD=postgres
    ports:
    - 5432:5432
    volumes:
    - db:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready, -d, db_prod]
      start_period: 10s
      interval: 30s
      timeout: 1s
      retries: 5

volumes:
  db:
    driver: local
networks:
  db:
    internal: false
  backend:
    internal: false
