version: '3.9'
services:

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080

    healthcheck:
      test: ["CMD-SHELL", "curl", "localhost:8080/healtz"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
    ports:
        - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db:
  node-modules:
    driver: local
