/*
 license x
*/

/*
 * O801 API
 *
 * Create and Get User
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"database/sql"
	"net/http"
)

// HealthCheckAPIService is a service that implements the logic for the HealthCheckAPIService
// This service should implement the business logic for every endpoint for the HealthCheckAPI API.
// Include any external packages or services that will be required by this service.
type HealthCheckAPIService struct {
	db *sql.DB
}

// NewHealthCheckAPIService creates a default api service.
func NewHealthCheckAPIService(db *sql.DB) HealthCheckAPIServicer {
	return &HealthCheckAPIService{
		db: db,
	}
}

// HealthGet - Returns the health of the service.
func (s *HealthCheckAPIService) HealthGet(_ context.Context) (ImplResponse, error) {
	if err := s.db.Ping(); err != nil {
		return Response(http.StatusServiceUnavailable, nil), nil
	}

	return Response(http.StatusOK, nil), nil
}

// LivenessGet - Returns whether it is currently operational and responsive.
func (s *HealthCheckAPIService) LivenessGet(_ context.Context) (ImplResponse, error) {
	return Response(http.StatusOK, nil), nil
}
