/*
 * O801 API
 *
 * Create and Get User
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)

// HealthCheckAPIRouter defines the required methods for binding the api requests to a responses for the HealthCheckAPI
// The HealthCheckAPIRouter implementation should parse necessary information from the http request,
// pass the data to a HealthCheckAPIServicer to perform the required actions, then write the service results to the http response.
type HealthCheckAPIRouter interface {
	HealthzGet(http.ResponseWriter, *http.Request)
	LivenessGet(http.ResponseWriter, *http.Request)
}

// MonitoringAPIRouter defines the required methods for binding the api requests to a responses for the MonitoringAPI
// The MonitoringAPIRouter implementation should parse necessary information from the http request,
// pass the data to a MonitoringAPIServicer to perform the required actions, then write the service results to the http response.
type MonitoringAPIRouter interface {
	MetricsGet(http.ResponseWriter, *http.Request)
}

// ServicesAPIRouter defines the required methods for binding the api requests to a responses for the ServicesAPI
// The ServicesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ServicesAPIServicer to perform the required actions, then write the service results to the http response.
type ServicesAPIRouter interface {
	CreateUser(http.ResponseWriter, *http.Request)
	GetUser(http.ResponseWriter, *http.Request)
}

// HealthCheckAPIServicer defines the api actions for the HealthCheckAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type HealthCheckAPIServicer interface {
	HealthzGet(context.Context) (ImplResponse, error)
	LivenessGet(context.Context) (ImplResponse, error)
}

// MonitoringAPIServicer defines the api actions for the MonitoringAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type MonitoringAPIServicer interface {
	MetricsGet(context.Context) (ImplResponse, error)
}

// ServicesAPIServicer defines the api actions for the ServicesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ServicesAPIServicer interface {
	CreateUser(context.Context, string) (ImplResponse, error)
	GetUser(context.Context, float32) (ImplResponse, error)
}
