/*
 * O801 API
 *
 * Create and Get User
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// MonitoringAPIService is a service that implements the logic for the MonitoringAPIServicer
// This service should implement the business logic for every endpoint for the MonitoringAPI API.
// Include any external packages or services that will be required by this service.
type MonitoringAPIService struct {
}

// NewMonitoringAPIService creates a default api service
func NewMonitoringAPIService() MonitoringAPIServicer {
	return &MonitoringAPIService{}
}

// MetricsGet - Returns whether it is currently operational and responsive.
func (s *MonitoringAPIService) MetricsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update MetricsGet with the required logic for this service method.
	// Add api_monitoring_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("MetricsGet method not implemented")
}
