name: Performance Tests

on:
  push:
    branches:
    - main

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go (or the required runtime)
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Run performance tests
      run: |
        echo "run performance tests and upload"
