name: Performance Tests

on:
  push:
    branches:
    - main

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go (or the required runtime)
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Run performance tests
      run: |
        echo "run performance tests and upload"
